#!/usr/bin/perl

use strict;
use warnings;

use DBI;

my $db   = $ENV{YGG_DB};
my $host = $ENV{YGG_HOST};
my $port = $ENV{YGG_MYSQL_PORT};
my $user = $ENV{YGG_USER};
my $pass = $ENV{YGG_PASSWORD};

my $dbh = DBI->connect( "DBI:mysql:database=$db;host=$host;port=$port", $user, $pass );
unless( $dbh ) {
    die "No database?\n";
}

my $sth = $dbh->prepare( "show tables" );
$sth->execute();

my $tables =  $sth->fetchall_arrayref();
for my $t ( @$tables ) {
    print "Dropping $t->[0]\n";
    $dbh->do( "drop table $t->[0]" );
}
