#!/usr/bin/perl

use strict;
use warnings;

use FindBin qw($Bin);
use lib qq($Bin/../lib/perl);

use Yggdrasil;

new Yggdrasil(
	      user      => $ENV{YGG_USER},
	      password  => $ENV{YGG_PASSWORD},
	      host      => $ENV{YGG_HOST},
	      port      => $ENV{YGG_PORT},
	      db        => $ENV{YGG_DB},
	      engine    => $ENV{YGG_ENGINE},
	      namespace => 'Ygg',
	     );


my $host = define Yggdrasil::Entity 'Host';
# Boom, Ygg::Host && Ygg::Host::Property exists, oh, and the DB has
# been properly populated (MetaEntity).

my $ippack = define $package 'IP', 'Type' => 'IP';
define Ygg::Host 'Serial';

my $nommo = Ygg::Host->new( 'nommo' );
$nommo->property( 'ip' , '129.240.222.179' );


$nommo = Ygg::Host->get( 'nommo' );

my $roompack = define Yggdrasil::Entity 'Room';
define Ygg::Room 'use', type => 'Text';

my $b810 = Ygg::Room->new( 'B810' );
$b810->property( "use", "Terminal room" );

define Yggdrasil::Relation $host, 'Room';
$b810->relate( $nommo );


define Yggdrasil::Entity 'Person';
define Yggdrasil::Entity 'Student', 'Person';
define Yggdrasil::Entity 'Student', 'Person';

