#!/usr/bin/perl

use strict;
use warnings;

use Preamble qw|getopts status status_die|;

my $opts = getopts();

my $ygg = new Yggdrasil( %$opts );
status_die( "Yggdrasil", $ygg );

my $connect = $ygg->connect( %$opts );
status_die( "Connect", $connect, 1 );

my $login = $ygg->login( user => $opts->{yuser}, password => $opts->{ypass} );
status_die( "Login", $login, 1 );

my $bark = $ygg->define_user( user => "bark", password => "secret" );
status( "User", $bark, 1 );

my $boss = $ygg->define_role( role => "Boss" );
status( "Role", $boss, 1 );

exit;

my $hoste = $ygg->get_entity( 'Host' );
status( "Entity", $hoste, 1 );
my $ip = $hoste->define_property( 'ip', 'type' => 'text' );
status( "Property", $ip, 1 );

$boss->grant( $hoste, "w" );
$boss->revoke( $hoste, "w" );

$boss->grant( $ip, "r" );

$boss->add( $bark );
$boss->remove( $bark );

